In [3]:
import numpy as np
import pandas as pd
from tensorflow.keras.models import load_model
import pickle
import json

# Load the Models
with open('final_pipeline.pkl', 'rb') as file_1:
  final_pipeline = pickle.load(file_1)
with open('Drop_Columns.txt','r') as file_2:
  Drop_Columns = json.load(file_2)

model_seq2 = load_model('model_seq2.h5')

WARNING:tensorflow:Error in loading the saved optimizer state. As a result, your model is starting with a freshly initialized optimizer.

In [4]:
# data loading
df_inf = pd.read_csv('h8dsft_p2m1_Ahmad Luay Adnani_inference.csv')
df_inf_copy = df_inf.copy()
df_inf_copy = df_inf.drop(['Unnamed: 0'],axis=1)
df_inf_copy

,user_id,age,gender,region_category,membership_category,joining_date,joined_through_referral,preferred_offer_types,medium_of_operation,internet_option,...,avg_time_spent,avg_transaction_value,avg_frequency_login_days,points_in_wallet,used_special_discount,offer_application_preference,past_complaint,complaint_status,feedback,churn_risk_score
0,972706cb0db0068e,46,F,Town,Premium Membership,2015-03-27,No,Credit/Debit Card Offers,Smartphone,Mobile_Data,...,1447.387929,11839.58,29.0,727.91,Yes,No,No,Not Applicable,No reason specified,0
1,82d62cc806fb2816,25,M,Town,Premium Membership,2016-09-07,NaN,Without Offers,Smartphone,Wi-Fi,...,114.170000,46885.80,8.0,793.11,No,Yes,Yes,Unsolved,No reason specified,0
2,a596b4679c30ef3e,64,M,NaN,Basic Membership,2017-09-07,Yes,Credit/Debit Card Offers,Smartphone,Wi-Fi,...,204.430000,42224.69,26.0,510.37,Yes,No,Yes,Solved,Too many ads,1
3,8c4761dbf8df1816,52,F,City,Gold Membership,2017-12-31,Yes,NaN,Smartphone,Wi-Fi,...,179.330000,48836.04,20.0,705.00,Yes,No,Yes,Solved in Follow-up,No reason specified,0
4,8f2f492e0c25eb41,60,M,Town,Basic Membership,2015-07-08,Yes,Credit/Debit Card Offers,Smartphone,Wi-Fi,...,38.940000,14104.52,21.0,677.41,Yes,No,Yes,No Information Available,Poor Customer Service,0
5,9bba07c5c386c34c,57,F,City,Silver Membership,2016-06-22,No,Gift Vouchers/Coupons,NaN,Mobile_Data,...,0.000000,8150.90,20.0,793.32,No,Yes,No,Not Applicable,No reason specified,0
6,8a205a969e23299d,17,M,NaN,Gold Membership,2015-05-19,No,Gift Vouchers/Coupons,Desktop,Wi-Fi,...,199.940000,75765.63,0.0,820.17,Yes,No,Yes,Solved,Quality Customer Care,0
7,91607fb18aafbfee,15,M,City,No Membership,2017-11-15,Yes,Gift Vouchers/Coupons,Desktop,Fiber_Optic,...,67.550000,32777.77,23.0,533.44,Yes,No,No,Not Applicable,Poor Customer Service,1
8,847bddd58ff99d7e,32,M,Town,Basic Membership,2016-02-02,Yes,Without Offers,Smartphone,Mobile_Data,...,119.980000,1888.81,28.0,628.93,No,Yes,No,Not Applicable,Too many ads,1
9,8c92ce118df969a1,29,M,Village,Platinum Membership,2016-10-19,No,Credit/Debit Card Offers,NaN,Fiber_Optic,...,145.070000,28873.91,19.0,715.50,No,Yes,No,Not Applicable,Too many ads,0

In [5]:
# Removing unnecessary features
df_inf_final = df_inf_copy.drop(Drop_Columns,axis=1).sort_index()
df_inf_final

,region_category,membership_category,joined_through_referral,preferred_offer_types,medium_of_operation,avg_time_spent,avg_transaction_value,avg_frequency_login_days,points_in_wallet,offer_application_preference,past_complaint,feedback,churn_risk_score
0,Town,Premium Membership,No,Credit/Debit Card Offers,Smartphone,1447.387929,11839.58,29.0,727.91,No,No,No reason specified,0
1,Town,Premium Membership,NaN,Without Offers,Smartphone,114.170000,46885.80,8.0,793.11,Yes,Yes,No reason specified,0
2,NaN,Basic Membership,Yes,Credit/Debit Card Offers,Smartphone,204.430000,42224.69,26.0,510.37,No,Yes,Too many ads,1
3,City,Gold Membership,Yes,NaN,Smartphone,179.330000,48836.04,20.0,705.00,No,Yes,No reason specified,0
4,Town,Basic Membership,Yes,Credit/Debit Card Offers,Smartphone,38.940000,14104.52,21.0,677.41,No,Yes,Poor Customer Service,0
5,City,Silver Membership,No,Gift Vouchers/Coupons,NaN,0.000000,8150.90,20.0,793.32,Yes,No,No reason specified,0
6,NaN,Gold Membership,No,Gift Vouchers/Coupons,Desktop,199.940000,75765.63,0.0,820.17,No,Yes,Quality Customer Care,0
7,City,No Membership,Yes,Gift Vouchers/Coupons,Desktop,67.550000,32777.77,23.0,533.44,No,No,Poor Customer Service,1
8,Town,Basic Membership,Yes,Without Offers,Smartphone,119.980000,1888.81,28.0,628.93,Yes,No,Too many ads,1
9,Village,Platinum Membership,No,Credit/Debit Card Offers,NaN,145.070000,28873.91,19.0,715.50,Yes,No,Too many ads,0

## Handling Missing Values

In [6]:
# Check Missing Values in Data Inference

df_inf_final.isnull().sum()

region_category                 2
membership_category             0
joined_through_referral         1
preferred_offer_types           1
medium_of_operation             2
avg_time_spent                  0
avg_transaction_value           0
avg_frequency_login_days        0
points_in_wallet                0
offer_application_preference    0
past_complaint                  0
feedback                        0
churn_risk_score                0
dtype: int64

In [7]:
# Fill missing values in categorical data with 'Unknown'
df_inf_final = df_inf_final.fillna({'region_category':'Unknown','joined_through_referral':'Unknown','medium_of_operation':'Unknown','preferred_offer_types':'Unknown'})

In [8]:
# Transform Inference-Set

data_inf_transform = final_pipeline.transform(df_inf_final)
data_inf_transform

array([[-0.92260035,  0.42325585,  0.65168539,  0.        ,  1.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  1.        ,  0.        ,  1.        ,  0.        ,
         0.        ,  1.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  1.        ,  0.        ,  1.        ,
         0.        ,  1.        ,  0.        ,  1.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ],
       [ 0.95864668,  0.7737009 ,  0.17977528,  0.        ,  1.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  1.        ,  0.        ,  0.        ,  1.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  1.        ,
         0.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         1.        ,  0.        ,  1.        ,  1.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ],
       [ 0.70844283, -0.74600513,  0.58426966,  0.        ,  0.        ,
         1.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         1.        ,  1.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  1.        ,  0.        ,  1.        ,
         0.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         1.        ,  0.        ],
       [ 1.06333367,  0.30011634,  0.4494382 ,  1.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  1.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         1.        ,  0.        ,  0.        ,  1.        ,  0.        ,
         0.        ,  0.        ,  1.        ,  0.        ,  1.        ,
         0.        ,  0.        ,  1.        ,  1.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ],
       [-0.80102057,  0.15182219,  0.47191011,  0.        ,  1.        ,
         0.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         1.        ,  1.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  1.        ,  0.        ,  1.        ,
         0.        ,  0.        ,  1.        ,  0.        ,  1.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ],
       [-1.12060511,  0.77482964,  0.4494382 ,  1.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  1.        ,  1.        ,  0.        ,
         0.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  1.        ,  0.        ,
         1.        ,  1.        ,  0.        ,  1.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ],
       [ 2.5088879 ,  0.91914635,  0.        ,  0.        ,  0.        ,
         1.        ,  0.        ,  0.        ,  1.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  1.        ,  0.        ,
         0.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         0.        ,  1.        ,  0.        ,  0.        ,  1.        ,
         0.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  1.        ,  0.        ,
         0.        ,  0.        ],
       [ 0.20134134, -0.62200563,  0.51685393,  1.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  1.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         1.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         0.        ,  1.        ,  0.        ,  0.        ,  1.        ,
         0.        ,  1.        ,  0.        ,  0.        ,  1.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ],
       [-1.45674802, -0.10875413,  0.62921348,  0.        ,  1.        ,
         0.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         1.        ,  0.        ,  0.        ,  0.        ,  1.        ,
         0.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         1.        ,  1.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         1.        ,  0.        ],
       [-0.00821407,  0.35655305,  0.42696629,  0.        ,  0.        ,
         0.        ,  1.        ,  0.        ,  0.        ,  0.        ,
         1.        ,  0.        ,  0.        ,  1.        ,  0.        ,
         0.        ,  1.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  1.        ,  0.        ,
         1.        ,  1.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         1.        ,  0.        ]])

In [9]:
# Predict using Neural Network

y_pred_inf = model_seq2.predict(data_inf_transform)
y_pred_inf = np.where(y_pred_inf >= 0.5, 1, 0)
y_pred_inf

1/1 [==============================] - 0s 217ms/step

array([[0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0]])

In [10]:
# Create Prediction DataFrame

y_pred_inf_df = pd.DataFrame(y_pred_inf, columns=['churn_risk_score_prediction'],index=df_inf_final.index)
y_pred_inf_df

   churn_risk_score_prediction
0                            0
1                            0
2                            1
3                            0
4                            1
5                            0
6                            0
7                            1
8                            1
9                            0

In [11]:
# Comparing the real Classes with predicted classification
model_inf = pd.concat([df_inf_copy['churn_risk_score'], y_pred_inf_df['churn_risk_score_prediction']], axis=1).sort_index()
model_inf

   churn_risk_score  churn_risk_score_prediction
0                 0                            0
1                 0                            0
2                 1                            1
3                 0                            0
4                 0                            1
5                 0                            0
6                 0                            0
7                 1                            1
8                 1                            1
9                 0                            0

Based on the prediction of data inference, apparently there is prediction with different results of the actual `churn_risk_score`, which is customer #4. This data inference prediction reflects the model's `precision`, `recall`, and` accuracy` which is around **92-94%**.